# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-20 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Idade',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Idade'),
            preserve_default=False,
        ),
    ]
