# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-20 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_auto_20171220_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DimPrioridade',
        ),
    ]
