# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0008_auto_20171220_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='FluxoInterno',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Queixa',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='DimQueixa',
        ),
    ]
