# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0014_auto_20171226_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Data',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
