# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-20 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_auto_20171220_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='prioridade2',
            field=models.CharField(blank=True, choices=[('VERMELHO', '1-EMERGENCIA (VERMELHO)'), ('LARANJA', '2-MUITO URGENTE (LARANJA)'), ('AMARELO', '3-URGENTE (AMARELO)'), ('VERDE', '4-POUCO URGENTE (VERDE)'), ('AZUL', '5-NÃO URGENTE (AZUL)'), ('BRANCO', '6-ELETIVO (BRANCO)')], max_length=9, null=True, verbose_name='Prioridade Clínica2'),
        ),
    ]
