# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0011_auto_20171221_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='HoraFimReclass',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Fim da Reclassificação'),
        ),
    ]
