# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0012_auto_20171221_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['-Data', '-HoraChegada']},
        ),
    ]
