# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0013_auto_20171226_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Data',
            field=models.DateField(default=datetime.datetime(2017, 12, 26, 12, 50, 52, 30049, tzinfo=utc), verbose_name='Data'),
        ),
    ]
