# Generated by Django 2.0.3 on 2018-04-02 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0018_auto_20180329_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Classificador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Classificador', to='formulario.DimClassificador', verbose_name='Classificador'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Discriminador2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Discriminador2', to='formulario.DimDiscriminador', verbose_name='Discriminador'),
        ),
    ]
