# Generated by Django 2.0.3 on 2018-04-02 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0019_auto_20180401_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Discriminador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Discriminador', to='formulario.DimDiscriminador', verbose_name='Discriminador'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Discriminador2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Discriminador2', to='formulario.DimDiscriminador', verbose_name='Discriminador'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Fluxograma',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='formulario.DimFluxograma', verbose_name='Fluxograma'),
        ),
    ]
