# Generated by Django 2.0.3 on 2018-04-02 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0020_auto_20180401_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Classificador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Classificador', to='formulario.DimClassificador', verbose_name='Classificador'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Discriminador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Discriminador', to='formulario.DimDiscriminador', verbose_name='Discriminador'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Fluxograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.DimFluxograma', verbose_name='Fluxograma'),
        ),
    ]
